#pragma once
#define TAPPING_TERM 200

#define COMBO_ONLY_FROM_LAYER 1 //QWERTY
#define COMBO_VARIABLE_LEN 2
#define COMBO_TERM 50
#define COMBO_SHOULD_TRIGGER

#define TAPPING_TOGGLE 2

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
